title: 9dogs — Unit Converter 2021
description: Simple, fast, and clean unit converter for iPhone.
email: weiqiaochun@gmail.com
url: https://9dogs.com
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default

social:
  github: 9dogs
app_store_url: https://apps.apple.com/us/app/unit-converter-2021/id1515666116
